### ISSUE TITLE
First pass blob detection: intensity threshold parameter 

### ISSUE THREAD

**Issue by JennyVoPhamhi** [czbiohub/instapaper#1]
Figure out how to map the intensity distribution from gaussian parameter extraction to the optimal intensity threshold parameter to be used by blob_log() -- the “minimum threshold for the scale space maxima,” as stated in the documentation of blob_log(). Alternatively, at least map the intensity distribution from gaussian parameter extraction to a range of possible intensity threshold parameters to be tried by blob_log() (such that the intensity threshold which results in the best precision and recall can be considered the optimal intensity threshold.

**Comment by kevinyamauchi** [comment]
Hey, @JennyVoPhamhi . Can we close this issue?

**Comment by JennyVoPhamhi** [comment]
Yes! I'll go ahead and close it. Thank you for catching this!
