### ISSUE TITLE
First pass blob detection: max sigma parameter

### ISSUE THREAD

**Issue by JennyVoPhamhi** [czbiohub/instapaper#2]
Find a mapping from the sigma distribution (found by Gaussian fit parameter extraction) to the actual optimal max_sigma (the parameter taken in by blob_log()) found when running blob_log() with fixed intensity threshold and varied max_sigma.

**Comment by kevinyamauchi** [comment]
Hey, @JennyVoPhamhi . Can we close this issue?

**Comment by JennyVoPhamhi** [comment]
Yes!
